name = "EfficientFrontier"
uuid = "cc5db6c5-6ee2-4027-b902-77472ae9c2f7"
authors = ["Pharos Abad"]
version = "0.2.1"

[deps]
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"



[compat]
Clarabel = "0.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
